engines:
  radon:
    enabled: true
    config:
      python_version: 2
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
        python:

# required for grades to appear in web UI
ratings:
  paths:
  - "**.py"
  - "psi/app/static/js/*.js"

exclude_paths:
- "psi/migrations/"
- "psi/static/ckeditor/"
- "psi/static/chart.js/"
- "psi/static/Font-Awesome-4.6.3/"
- "psi/static/bootbox/"
- "psi/static/lightbox2/"
- "tests/"
