engines:
  radon:
    enabled: true
    config:
      python_version: 2
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
        python:

# required for grades to appear in web UI
ratings:
  paths:
  - "**.py"

exclude_paths:
- psi/migrations
- psi/app/static/ckeditor
- psi/app/static/chart.js
- psi/app/static/Font-Awesome-4.6.3
- psi/app/static/bootbox
- psi/app/static/lightbox2
- tests
